version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install NVM
          command: choco install -y nvm
      - run:
          name: Install Node environment
          command: |
            $NODE_VERSION = Get-Content .nvmrc
            nvm install $NODE_VERSION
            nvm use $NODE_VERSION
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - run:
          name: Verify versions
          shell: bash.exe
          command: |
            node --version
            nvm --version
            yarn --version
      - run:
          name: Test
          command: |
            yarn init -y
            yarn set version 4.0.1
            echo "nodeLinker: node-modules" | tee .yarnrc.yml
            yarn add -D supabase
      - run: yarn supabase -h
workflows:
  my-workflow:
    jobs:
      - build
